spring:
  cache:
    type: redis
  main:
    allow-bean-definition-overriding: true
  application:
    name: srping-tutorial
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://103.70.12.113:5432/airport
    username: postgres
    password: 123@123aA
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      schema: public
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.batch_size: 1000
        order_inserts: true
        default_schema: gtel
  data:
    redis:
      host: 103.70.12.113
      port: 6379
server:
  port: 8088
  servlet:
    context-path: /api
logging:
  level:
    com.gtel: debug
token:
  impl: 1
jwt:
  secretkey: 123321asdf123321asdf123321asdfgythhh